//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeansOffice5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Subject
    {
        public int IdStudentSubject { get; set; }
        public int IdStudent { get; set; }
        public int IdSubject { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
